### ISSUE TITLE
(How) is removing explicit substitutions NbE?

### ISSUE THREAD

**Issue by NathanielB123** [txa/substitution#12]
This is a follow-up from the Zoom call. I definitely could have misheard, misunderstood or misremembered, but I think on that call, it was said that one of the things we should try and achieve is to use NbE to convert between the initial CwF and our implicit substitution syntax (i.e. the syntax defined in `paper.lagda`).

I'm definitely not an expert here, but in the few presentations of NbE I have seen `reify`/`quote` and `reflect`/`unquote` are mutually recursive. Also, there are typically not just terms and normal forms, but also some representation of _values_ (I think in "NORMALISATION BY EVALUATION FOR TYPE THEORY, IN TYPE THEORY", the analogous thing is the logical predicate) which represents lambdas as meta-language functions.

For converting from the initial CwF to our implicit substition syntax and back, I don't think either of these things will be necessary. Converting into the CwF will just be a case of recursing on the syntax and calling appropriate CwF constructors, and the other direction will just involve calling the recursor of the initial CwF with the proof that our implicit sub syntax satisfies the CwF laws. 

Obviously proving that these functions are inverses of each other will take a bit more effort, but I would have assumed this should only require induction on the syntaxes and lemmas we have already proven?

Admittedly, the presentations of NbE I am using as a reference to were all focussed on reducing terms to fully normal forms (as opposed to "substitution normal forms"), so maybe some of these details are artifacts of that goal, but basically, I'm confused about:
1. What actually is the definition of "NbE"?
2.  How one could one apply "NbE" usefully to our scenario of removing explicit substitutions (if that is indeed the goal)?

**Comment by txa** [comment]
I shouldn't have said NbE because this is a bit of an overkill here since we only define substitutions.

We have two cwfs: initial and recursive. Since recursive is a cwf we get a map from initial to recursive. We also have an embedding form recursive to initial which just maps "substitution normal forms" to full substitution terms. Ok we want to show that they are inverse. This should be easy but I am too tired today to write a full sketch. We don't need to do NbE with mutually defined functions, I think.

**Comment by NathanielB123** [comment]
Cool cool, all makes sense. I think I can give that a try
