### ISSUE TITLE
summarize category laws

### ISSUE THREAD

**Issue by txa** [txa/substitution#7]
Do we have a category of terms? Not really because the identity laws only hold for V=T.
This can be addressed by defining sort polymorphic id to be tm⊑ idv or something like this. 
Alternatively we can use the definition of the category I use in cwf-simple.lagda.md
which is maybe a good idea.

I will draft another section.

**Comment by NathanielB123** [comment]
I think it might be easier to state the category laws if we change our definition of substitutions from:
```agda
record _⊨_ (Γ Δ : Con) : Set where
  constructor tms
  field
    {qq} : Sort
    xss : Γ ⊨[ qq ] Δ
```
to just `_⊨_ = _⊨[ T ]_`.

Otherwise we have issues like there being two equivalent representations of `ε` (`tms {qq = V} ε` and `tms {qq = T} ε` which makes it impossible to prove `•-η`.

**Comment by NathanielB123** [comment]
Honestly we could probably do the same thing for single terms (`_⊢_ = _⊢[ T ]_`), though I'm not if we would gain anything vs the `Sort`-polymorphic definition in that case.

**Comment by NathanielB123** [comment]
The downside is that I think we then really would need to prove lemmas about identity substitutions at sort `T` (either by defining `id` as sort-polymorphic in the first place, or lifting it like `tm⊑ idv` as you mention - maybe the latter is nice because we can then reuse the `id∘` lemmas for renamings. I'll give it a try

**Comment by txa** [comment]
Yes, I agree. I think I prefer the record (and yes the qq field should be hidden). 

One minor issue is that we have now two compositions, the one indexed by sorts and the one for the record. Any suggestions?

Or can we do the whole proof just with the record? I think the termination checker may not play ball?

**Comment by NathanielB123** [comment]
> Yes, I agree. I think I prefer the record (and yes the qq field should be hidden).
> 
> One minor issue is that we have now two compositions, the one indexed by sorts and the one for the record. Any suggestions?
> 
> Or can we do the whole proof just with the record? I think the termination checker may not play ball?

I got relatively far just filling in the record directly and the termination checker didn't complain (most of the fields just involve matching on the records and then calling the actual operation on the inner terms/substitutions instead of actually needing induction, so termination is trivial, but maybe one of the remaining cases will prove more problematic...):
```
stlc : CwF
stlc .CwF.Con = Con
stlc .CwF.Ty = Ty
stlc .CwF._⊢_ = _⊢_
stlc .CwF._⊨_ = _⊨_
stlc .CwF.id = tms id
stlc .CwF._∘_ (tms xs) (tms ys) = tms (xs ∘ ys)
stlc .CwF.id∘ = cong tms id∘
stlc .CwF.∘id = cong tms ∘id
stlc .CwF.∘∘ = cong tms (sym ∘∘)
stlc .CwF._[_] (tm x) (tms xs) = tm (x [ xs ])
stlc .CwF.[id] = cong tm [id]
stlc .CwF.[∘] {t = tm x} = cong tm (sym ([∘] {x = x}))
stlc .CwF.• = •
stlc .CwF.ε = tms {qq = V} ε
-- We are stuck!
stlc .CwF.•-η {δ = tms ε} = {!!}
stlc .CwF._▷_ = _▷_
-- Here, we need to coerce 'xs' and 'x' to 'Sort' 'q ⊔ r'. 
-- Do-able, but a bit painful...
stlc .CwF._,_ (tms {qq = q} xs) (tm {qq = r} x) 
  = tms {qq = q ⊔ r} ({!xs!} , tm⊑ (⊑⊔r {q = q}) x)
stlc .CwF.π₀ (tms (xs , x)) = tms xs
stlc .CwF.π₁ (tms (xs , x)) = tm x
stlc .CwF.▷-β₀ = {!!}
stlc .CwF.▷-β₁ = {!!}
stlc .CwF.▷-η = {!!}
stlc .CwF.π₀∘ {θ = tms (xs , x)} = refl
stlc .CwF.π₁∘ {θ = tms (xs , x)} = refl
stlc .CwF.o = o
stlc .CwF._⇒_ = _⇒_
stlc .CwF._·_ (tm x) (tm y) = tm {qq = T} (tm⊑ ⊑t x · tm⊑  ⊑t y)
stlc .CwF.ƛ_ (tm x) = tm {qq = T} (ƛ tm⊑ ⊑t x)
stlc .CwF.·[] = {!!}
stlc .CwF.ƛ[] = {!!}
```

Other than the clutter with needing to coerce terms/substitutions (which yeah I agree is not great with the record or `_⊢[ T ]_` approaches) the main problem I have with the record definition that I don't think proving `•-η` is possible (i.e. `ε` at sort `V` and `T` cannot be proved equal). Do you have any ideas on how to fix that?

**Comment by NathanielB123** [comment]
Also btw, I just have one case left for the `_⊢_ = _⊢[ T ]_`/`_⊨_ = _⊨[ T ]_` approach - I don't think it turned out _that_ horrible?

```agda
tm*⊑ : q ⊑ s → Γ ⊨[ q ] Δ → Γ ⊨[ s ] Δ
tm*⊑ q⊑s ε = ε
tm*⊑ q⊑s (σ , x) = tm*⊑ q⊑s σ , tm⊑ q⊑s x

_⊢_ = _⊢[ T ]_
_⊨_ = _⊨[ T ]_

⊑∘ : xs ∘ ys ≡ tm*⊑ v⊑t xs ∘ ys
⊑∘ {xs = ε} = refl
⊑∘ {xs = xs , x} = cong₂ _,_ ⊑∘ refl

⊑⁺ : tm*⊑ v⊑t xs ⁺ A ≡ tm*⊑ v⊑t (xs ⁺ A)
⊑⁺ {xs = ε} = refl
⊑⁺ {xs = xs , x} {A = A} = cong₂ _,_ ⊑⁺ 
  (` x [ id ⁺ A ] 
  ≡⟨ cong `_ (⁺-nat[]v {i = x}) ⟩ 
  ` suc (x [ id ]) A
  ≡⟨ cong (λ y → ` suc y A) [id] ⟩
  ` suc x A ∎)

⊑^ : tm*⊑ v⊑t xs ^ A ≡ tm*⊑ v⊑t (xs ^ A)
⊑^ = cong (_, ` zero) ⊑⁺

`[⊑] : ∀ {x : Γ ⊢[ V ] A} {ys : Δ ⊨[ V ] Γ} → ` x [ ys ] ≡ x [ tm*⊑ v⊑t ys ]
`[⊑] {x = zero} {ys = ys , y} = refl
`[⊑] {x = suc x _} {ys = ys , y} = `[⊑] {x = x}

[⊑] : ∀ {x : Γ ⊢[ T ] A} {ys : Δ ⊨[ V ] Γ} → x [ ys ] ≡ x [ tm*⊑ v⊑t ys ]
[⊑] {x = ` x} = `[⊑] {x = x}
[⊑] {x = x · y} = cong₂ _·_ ([⊑] {x = x}) ([⊑] {x = y})
[⊑] {x = ƛ x} {ys = ys} = 
  ƛ x [ ys ^ _ ]
  ≡⟨ cong ƛ_ ([⊑] {x = x}) ⟩ 
  ƛ x [ tm*⊑ v⊑t (ys ^ _) ]
  ≡⟨ cong (λ ρ → ƛ x [ ρ ]) (sym ⊑^) ⟩
  ƛ x [ tm*⊑ v⊑t ys ^ _ ] ∎

∘⊑ : ∀ {xs : Δ ⊨[ T ] Γ} {ys : Θ ⊨[ V ] Δ} → xs ∘ ys ≡ xs ∘ tm*⊑ v⊑t ys
∘⊑ {xs = ε} {ys = ys} = refl
∘⊑ {xs = xs , x} = cong₂ _,_ ∘⊑ ([⊑] {x = x})

^∘id, : xs ^ A ≡ (xs ∘ (id ⁺ A) , zero)

stlc : CwF
stlc .CwF.Con = Con
stlc .CwF.Ty = Ty
stlc .CwF._⊢_ = _⊢_
stlc .CwF._⊨_ = _⊨_
stlc .CwF.id = tm*⊑ v⊑t id
stlc .CwF._∘_ = _∘_
stlc .CwF.id∘ = sym ⊑∘ ∙ id∘
stlc .CwF.∘id = sym ∘⊑ ∙ ∘id
stlc .CwF.∘∘ = sym ∘∘
stlc .CwF._[_] = _[_]
stlc .CwF.[id] {t = x} = sym ([⊑] {x = x}) ∙ [id]
stlc .CwF.[∘] {t = x} = sym ([∘] {x = x})
stlc .CwF.• = •
stlc .CwF.ε = ε
stlc .CwF.•-η {δ = ε} = refl
stlc .CwF._▷_ = _▷_
stlc .CwF._,_ = _,_
stlc .CwF.π₀ (xs , x) = xs
stlc .CwF.π₁ (xs , x) = x
stlc .CwF.▷-β₀ = refl
stlc .CwF.▷-β₁ = refl
stlc .CwF.▷-η {δ = xs , x} = refl
stlc .CwF.π₀∘ {θ = xs , x} = refl
stlc .CwF.π₁∘ {θ = xs , x} = refl
stlc .CwF.o = o
stlc .CwF._⇒_ = _⇒_
stlc .CwF._·_ = _·_
stlc .CwF.ƛ_ = ƛ_
stlc .CwF.·[] = refl
stlc .CwF.ƛ[] {t = x} {δ = ys} = 
  {!!} 
  ≡⟨ cong ƛ_ {!^∘id, !} ⟩ 
  {!!} ∎
```

**Comment by NathanielB123** [comment]
Finished the last case of the `_⊢_ = _⊢[ T ]_`/`_⊨_ = _⊨[ T ]_` approach! Will create a PR (if you have an idea of how to solve the `•-η` problem I'm happy to keep working on the record approach, but until then I think I'm stuck there...)

```agda
stlc .CwF.ƛ[] {A = A} {t = x} {δ = ys} = 
  ƛ x [ ys ^ A ]
  ≡⟨ cong (λ ρ → ƛ x [ ρ , ` zero ]) (∘id⁺ {A = A} {xs = ys}) ⟩ 
  ƛ x [ ys ∘ id ⁺ A , ` zero ]
  ≡⟨ cong (λ ρ → ƛ x [ ρ , ` zero ]) (∘⊑ {xs = ys} {ys = id ⁺ A}) ⟩
  ƛ x [ ys ∘ tm*⊑ v⊑t (id-poly ⁺ A) , ` zero ] ∎
```
